.TH "/Users/maurice/git/VCU-STM32F767ZI/inc/Header_VCU Directory Reference" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maurice/git/VCU-STM32F767ZI/inc/Header_VCU Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBMS\&.h\fP"
.br
.RI "This file contains the Battery Management System class\&. "
.ti -1c
.RI "file \fBcanTempSensor\&.h\fP"
.br
.RI "This file Provides a Temperature Sensor Class for CAN\&. "
.ti -1c
.RI "file \fBInverter\&.h\fP"
.br
.ti -1c
.RI "file \fBSensors\&.h\fP"
.br
.RI "This file contains all \fBSensors\fP\&. "
.ti -1c
.RI "file \fBVehicleModel\&.h\fP"
.br
.RI "This file contains the Vehicle Model class\&. "
.in -1c
