.TH "/Users/maurice/git/VCU-STM32F767ZI/src/Class_VCU Directory Reference" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maurice/git/VCU-STM32F767ZI/src/Class_VCU Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcanTempSensor\&.cpp\fP"
.br
.RI ": This file provides all \fBSensors\fP and the initialization "
.ti -1c
.RI "file \fBSensors\&.cpp\fP"
.br
.RI ": This file provides all \fBSensors\fP and the Initialization "
.in -1c
