C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/src/adc.c
NAME
C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/src/adc.c
SYNOPSIS
#include 'adc.h'
Functions
void MX_ADC1_Init (void)
void HAL_ADC_MspInit (ADC_HandleTypeDef *adcHandle)
void HAL_ADC_MspDeInit (ADC_HandleTypeDef *adcHandle)
Variables
ADC_HandleTypeDef hadc1
Function Documentation
void HAL_ADC_MspDeInit (ADC_HandleTypeDef * adcHandle)
ADC1 GPIO Configuration
 PA0/WKUP ------> ADC1_IN0 PA1 ------> ADC1_IN1
Definition at line 92 of file adc.c.
References Throttle_IN1_Pin, and Throttle_IN2_Pin.
void HAL_ADC_MspInit (ADC_HandleTypeDef * adcHandle)
ADC1 GPIO Configuration
 PA0/WKUP ------> ADC1_IN0 PA1 ------> ADC1_IN1
Definition at line 64 of file adc.c.
References Throttle_IN1_Pin, and Throttle_IN2_Pin.
void MX_ADC1_Init (void)
Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Definition at line 30 of file adc.c.
References Error_Handler(), and hadc1.
Referenced by main().
Variable Documentation
ADC_HandleTypeDef hadc1
File Name : ADC.c Description : This file provides code for the configuration of the ADC instances.
Attention
(C) Copyright (c) 2019 STMicroelectronics. All rights reserved.
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License. You may obtain a copy of the License at: opensource.org/licenses/BSD-3-Clause
Definition at line 27 of file adc.c.
Referenced by MX_ADC1_Init().
Author
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code.