.TH "/Users/maurice/git/VCU-STM32F767ZI/inc/adc.h" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maurice/git/VCU-STM32F767ZI/inc/adc.h
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_ADC1_Init\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ADC_HandleTypeDef \fBhadc1\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void MX_ADC1_Init (void)"
Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
.PP
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time\&.
.PP
Definition at line 30 of file adc\&.c\&.
.PP
References Error_Handler(), and hadc1\&.
.PP
Referenced by main()\&.
.SH "Variable Documentation"
.PP 
.SS "ADC_HandleTypeDef hadc1"
File Name : \fBADC\&.h\fP Description : This file provides code for the configuration of the ADC instances\&.
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2019 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause
.PP
File Name : \fBADC\&.c\fP Description : This file provides code for the configuration of the ADC instances\&.
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2019 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
Definition at line 27 of file adc\&.c\&.
.PP
Referenced by MX_ADC1_Init()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
