.TH "BMS" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMS
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BMS\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBMS\fP ()"
.br
.ti -1c
.RI "virtual \fB~BMS\fP ()"
.br
.ti -1c
.RI "bool \fBsetVoltage\fP (float volt)"
.br
.ti -1c
.RI "bool \fBsetCurrent\fP (float amp)"
.br
.ti -1c
.RI "bool \fBsetSoC\fP (float soc)"
.br
.ti -1c
.RI "bool \fBsetTemp\fP (unsigned short int tempArray[104])"
.br
.ti -1c
.RI "float \fBgetVoltage\fP ()"
.br
.ti -1c
.RI "float \fBgetCurrent\fP ()"
.br
.ti -1c
.RI "float \fBgetSoC\fP ()"
.br
.ti -1c
.RI "float \fBgetTemp\fP ()"
.br
.ti -1c
.RI "float \fBgetPeakTemp\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBsavePeakTemp\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBcurrent\fP"
.br
.ti -1c
.RI "float \fBvoltage\fP"
.br
.ti -1c
.RI "float \fBstateOfCharge\fP"
.br
.ti -1c
.RI "unsigned short int \fBpeakTemp\fP"
.br
.ti -1c
.RI "unsigned short int \fBoverallTemp\fP [104]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file BMS\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BMS::BMS ()"

.SS "virtual BMS::~BMS ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "float BMS::getCurrent ()"

.SS "float BMS::getPeakTemp ()"

.SS "float BMS::getSoC ()"

.SS "float BMS::getTemp ()"

.SS "float BMS::getVoltage ()"

.SS "bool BMS::savePeakTemp ()\fC [private]\fP"

.SS "bool BMS::setCurrent (float amp)"

.SS "bool BMS::setSoC (float soc)"

.SS "bool BMS::setTemp (unsigned short int tempArray[104])"

.SS "bool BMS::setVoltage (float volt)"

.SH "Member Data Documentation"
.PP 
.SS "float BMS::current\fC [private]\fP"

.PP
Definition at line 39 of file BMS\&.h\&.
.SS "unsigned short int BMS::overallTemp[104]\fC [private]\fP"

.PP
Definition at line 43 of file BMS\&.h\&.
.SS "unsigned short int BMS::peakTemp\fC [private]\fP"

.PP
Definition at line 42 of file BMS\&.h\&.
.SS "float BMS::stateOfCharge\fC [private]\fP"

.PP
Definition at line 41 of file BMS\&.h\&.
.SS "float BMS::voltage\fC [private]\fP"

.PP
Definition at line 40 of file BMS\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
