.TH "C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/inc Directory Reference" 3 "Fri Dec 13 2019" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBadc\&.h\fP"
.br
.ti -1c
.RI "file \fBcan\&.h\fP"
.br
.ti -1c
.RI "file \fBgpio\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.h\fP"
.br
.RI ": Header for \fBmain\&.c\fP file\&. This file contains the common defines of the application\&. "
.ti -1c
.RI "file \fBSensors\&.h\fP"
.br
.RI ": This file contains an Abstract for sensors "
.ti -1c
.RI "file \fBstm32f7xx_hal_conf\&.h\fP"
.br
.ti -1c
.RI "file \fBstm32f7xx_it\&.h\fP"
.br
.RI "This file contains the headers of the interrupt handlers\&. "
.ti -1c
.RI "file \fBsys\&.h\fP"
.br
.in -1c
