/Users/maurice/git/VCU-STM32F767ZI/src/can.c
NAME
/Users/maurice/git/VCU-STM32F767ZI/src/can.c
SYNOPSIS
#include 'can.h'
Functions
void MX_CAN1_Init (void)
void MX_CAN2_Init (void)
void HAL_CAN_MspInit (CAN_HandleTypeDef *canHandle)
void HAL_CAN_MspDeInit (CAN_HandleTypeDef *canHandle)
Variables
CAN_HandleTypeDef hcan1
CAN_HandleTypeDef hcan2
Function Documentation
void HAL_CAN_MspDeInit (CAN_HandleTypeDef * canHandle)
CAN1 GPIO Configuration
 PA11 ------> CAN1_RX PA12 ------> CAN1_TX
CAN2 GPIO Configuration
 PB12 ------> CAN2_RX PB6 ------> CAN2_TX
Definition at line 138 of file can.c.
References SysEl_RX_Pin, and SysEl_TX_Pin.
void HAL_CAN_MspInit (CAN_HandleTypeDef * canHandle)
CAN1 GPIO Configuration
 PA11 ------> CAN1_RX PA12 ------> CAN1_TX
CAN2 GPIO Configuration
 PB12 ------> CAN2_RX PB6 ------> CAN2_TX
Definition at line 76 of file can.c.
void MX_CAN1_Init (void)
Definition at line 30 of file can.c.
References Error_Handler(), and hcan1.
Referenced by main().
void MX_CAN2_Init (void)
Definition at line 52 of file can.c.
References Error_Handler(), and hcan2.
Referenced by main().
Variable Documentation
CAN_HandleTypeDef hcan1
File Name : CAN.c Description : This file provides code for the configuration of the CAN instances.
Attention
(C) Copyright (c) 2019 STMicroelectronics. All rights reserved.
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License. You may obtain a copy of the License at: opensource.org/licenses/BSD-3-Clause
Definition at line 26 of file can.c.
Referenced by MX_CAN1_Init().
CAN_HandleTypeDef hcan2
Definition at line 27 of file can.c.
Referenced by MX_CAN2_Init().
Author
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code.