C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/inc/can.h
NAME
C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/inc/can.h
SYNOPSIS
#include 'main.h'
Functions
void MX_CAN1_Init (void)
void MX_CAN2_Init (void)
void MX_CAN3_Init (void)
Variables
CAN_HandleTypeDef hcan1
CAN_HandleTypeDef hcan2
CAN_HandleTypeDef hcan3
Function Documentation
void MX_CAN1_Init (void)
Definition at line 32 of file can.c.
References Error_Handler(), and hcan1.
Referenced by main().
void MX_CAN2_Init (void)
Definition at line 54 of file can.c.
References Error_Handler(), and hcan2.
Referenced by main().
void MX_CAN3_Init (void)
Definition at line 76 of file can.c.
References Error_Handler(), and hcan3.
Referenced by main().
Variable Documentation
CAN_HandleTypeDef hcan1
File Name : CAN.h Description : This file provides code for the configuration of the CAN instances.
Attention
(C) Copyright (c) 2019 STMicroelectronics. All rights reserved.
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License. You may obtain a copy of the License at: opensource.org/licenses/BSD-3-Clause
File Name : CAN.c Description : This file provides code for the configuration of the CAN instances.
Attention
(C) Copyright (c) 2019 STMicroelectronics. All rights reserved.
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License. You may obtain a copy of the License at: opensource.org/licenses/BSD-3-Clause
Definition at line 27 of file can.c.
Referenced by MX_CAN1_Init().
CAN_HandleTypeDef hcan2
Definition at line 28 of file can.c.
Referenced by MX_CAN2_Init().
CAN_HandleTypeDef hcan3
Definition at line 29 of file can.c.
Referenced by MX_CAN3_Init().
Author
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code.