.TH "/Users/maurice/git/VCU-STM32F767ZI/src/can.c" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maurice/git/VCU-STM32F767ZI/src/can.c
.SH SYNOPSIS
.br
.PP
\fC#include 'can\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_CAN1_Init\fP (void)"
.br
.ti -1c
.RI "void \fBMX_CAN2_Init\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_CAN_MspInit\fP (CAN_HandleTypeDef *canHandle)"
.br
.ti -1c
.RI "void \fBHAL_CAN_MspDeInit\fP (CAN_HandleTypeDef *canHandle)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "CAN_HandleTypeDef \fBhcan1\fP"
.br
.ti -1c
.RI "CAN_HandleTypeDef \fBhcan2\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void HAL_CAN_MspDeInit (CAN_HandleTypeDef * canHandle)"
CAN1 GPIO Configuration 
.br
 PA11 ------> CAN1_RX PA12 ------> CAN1_TX
.PP
CAN2 GPIO Configuration 
.br
 PB12 ------> CAN2_RX PB6 ------> CAN2_TX
.PP
Definition at line 138 of file can\&.c\&.
.PP
References SysEl_RX_Pin, and SysEl_TX_Pin\&.
.SS "void HAL_CAN_MspInit (CAN_HandleTypeDef * canHandle)"
CAN1 GPIO Configuration 
.br
 PA11 ------> CAN1_RX PA12 ------> CAN1_TX
.PP
CAN2 GPIO Configuration 
.br
 PB12 ------> CAN2_RX PB6 ------> CAN2_TX
.PP
Definition at line 76 of file can\&.c\&.
.SS "void MX_CAN1_Init (void)"

.PP
Definition at line 30 of file can\&.c\&.
.PP
References Error_Handler(), and hcan1\&.
.PP
Referenced by main()\&.
.SS "void MX_CAN2_Init (void)"

.PP
Definition at line 52 of file can\&.c\&.
.PP
References Error_Handler(), and hcan2\&.
.PP
Referenced by main()\&.
.SH "Variable Documentation"
.PP 
.SS "CAN_HandleTypeDef hcan1"
File Name : \fBCAN\&.c\fP Description : This file provides code for the configuration of the CAN instances\&.
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2019 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
Definition at line 26 of file can\&.c\&.
.PP
Referenced by MX_CAN1_Init()\&.
.SS "CAN_HandleTypeDef hcan2"

.PP
Definition at line 27 of file can\&.c\&.
.PP
Referenced by MX_CAN2_Init()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
