.TH "C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/inc/can.h" 3 "Fri Dec 13 2019" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/inc/can.h
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_CAN1_Init\fP (void)"
.br
.ti -1c
.RI "void \fBMX_CAN2_Init\fP (void)"
.br
.ti -1c
.RI "void \fBMX_CAN3_Init\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "CAN_HandleTypeDef \fBhcan1\fP"
.br
.ti -1c
.RI "CAN_HandleTypeDef \fBhcan2\fP"
.br
.ti -1c
.RI "CAN_HandleTypeDef \fBhcan3\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void MX_CAN1_Init (void)"

.PP
Definition at line 32 of file can\&.c\&.
.PP
References Error_Handler(), and hcan1\&.
.PP
Referenced by main()\&.
.SS "void MX_CAN2_Init (void)"

.PP
Definition at line 54 of file can\&.c\&.
.PP
References Error_Handler(), and hcan2\&.
.PP
Referenced by main()\&.
.SS "void MX_CAN3_Init (void)"

.PP
Definition at line 76 of file can\&.c\&.
.PP
References Error_Handler(), and hcan3\&.
.PP
Referenced by main()\&.
.SH "Variable Documentation"
.PP 
.SS "CAN_HandleTypeDef hcan1"
File Name : \fBCAN\&.h\fP Description : This file provides code for the configuration of the CAN instances\&.
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2019 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause
.PP
File Name : \fBCAN\&.c\fP Description : This file provides code for the configuration of the CAN instances\&.
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2019 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
Definition at line 27 of file can\&.c\&.
.PP
Referenced by MX_CAN1_Init()\&.
.SS "CAN_HandleTypeDef hcan2"

.PP
Definition at line 28 of file can\&.c\&.
.PP
Referenced by MX_CAN2_Init()\&.
.SS "CAN_HandleTypeDef hcan3"

.PP
Definition at line 29 of file can\&.c\&.
.PP
Referenced by MX_CAN3_Init()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
