.TH "/Users/maurice/git/VCU-STM32F767ZI/inc/Header_VCU/canTempSensor.h" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maurice/git/VCU-STM32F767ZI/inc/Header_VCU/canTempSensor.h \- This file Provides a Temperature Sensor Class for CAN\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcanTempSensor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file Provides a Temperature Sensor Class for CAN\&. 


.PP
\fBAuthor\fP
.RS 4
Maurice Hugenschmidt
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
This Sensor class can receive data only from CAN 
.PP
Definition in file \fBcanTempSensor\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
