.TH "/Users/maurice/git/VCU-STM32F767ZI/src/gpio.c" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maurice/git/VCU-STM32F767ZI/src/gpio.c
.SH SYNOPSIS
.br
.PP
\fC#include 'gpio\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_GPIO_Init\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void MX_GPIO_Init (void)"
File Name : \fBgpio\&.c\fP Description : This file provides code for the configuration of all used GPIO pins\&.
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2019 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause Configure pins as Analog Input Output EVENT_OUT EXTI 
.PP
Definition at line 40 of file gpio\&.c\&.
.PP
References BOTS_Pin, HV_unlock_GPIO_Port, HV_unlock_Pin, HVOK_IN_Pin, LD1_Pin, and LD3_Pin\&.
.PP
Referenced by main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
