.TH "/Users/maurice/git/VCU-STM32F767ZI/inc/Header_VCU/Inverter.h" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maurice/git/VCU-STM32F767ZI/inc/Header_VCU/Inverter.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'stm32f7xx_hal_can\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInverter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
