.TH "/Users/maurice/git/VCU-STM32F767ZI/inc/main.h" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maurice/git/VCU-STM32F767ZI/inc/main.h \- : Header for main\&.c file\&. This file contains the common defines of the application\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f7xx_hal\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBOTS_Pin\fP   GPIO_PIN_1"
.br
.ti -1c
.RI "#define \fBBOTS_GPIO_Port\fP   GPIOF"
.br
.ti -1c
.RI "#define \fBHVOK_IN_Pin\fP   GPIO_PIN_2"
.br
.ti -1c
.RI "#define \fBHVOK_IN_GPIO_Port\fP   GPIOF"
.br
.ti -1c
.RI "#define \fBHV_unlock_Pin\fP   GPIO_PIN_3"
.br
.ti -1c
.RI "#define \fBHV_unlock_GPIO_Port\fP   GPIOF"
.br
.ti -1c
.RI "#define \fBThrottle_IN1_Pin\fP   GPIO_PIN_0"
.br
.ti -1c
.RI "#define \fBThrottle_IN1_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBThrottle_IN2_Pin\fP   GPIO_PIN_1"
.br
.ti -1c
.RI "#define \fBThrottle_IN2_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBLD1_Pin\fP   GPIO_PIN_0"
.br
.ti -1c
.RI "#define \fBLD1_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBINV1_RX_Pin\fP   GPIO_PIN_12"
.br
.ti -1c
.RI "#define \fBINV1_RX_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBLD3_Pin\fP   GPIO_PIN_14"
.br
.ti -1c
.RI "#define \fBLD3_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBSysEl_RX_Pin\fP   GPIO_PIN_11"
.br
.ti -1c
.RI "#define \fBSysEl_RX_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBSysEl_TX_Pin\fP   GPIO_PIN_12"
.br
.ti -1c
.RI "#define \fBSysEl_TX_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBINV2_TX_Pin\fP   GPIO_PIN_6"
.br
.ti -1c
.RI "#define \fBINV2_TX_GPIO_Port\fP   GPIOB"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBError_Handler\fP (void)"
.br
.RI "This function is executed in case of error occurrence\&. "
.in -1c
.SH "Detailed Description"
.PP 
: Header for main\&.c file\&. This file contains the common defines of the application\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
.SS "(C) Copyright (c) 2019 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
Definition in file \fBmain\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define BOTS_GPIO_Port   GPIOF"

.PP
Definition at line 62 of file main\&.h\&.
.SS "#define BOTS_Pin   GPIO_PIN_1"

.PP
Definition at line 61 of file main\&.h\&.
.SS "#define HV_unlock_GPIO_Port   GPIOF"

.PP
Definition at line 66 of file main\&.h\&.
.SS "#define HV_unlock_Pin   GPIO_PIN_3"

.PP
Definition at line 65 of file main\&.h\&.
.SS "#define HVOK_IN_GPIO_Port   GPIOF"

.PP
Definition at line 64 of file main\&.h\&.
.SS "#define HVOK_IN_Pin   GPIO_PIN_2"

.PP
Definition at line 63 of file main\&.h\&.
.SS "#define INV1_RX_GPIO_Port   GPIOB"

.PP
Definition at line 74 of file main\&.h\&.
.SS "#define INV1_RX_Pin   GPIO_PIN_12"

.PP
Definition at line 73 of file main\&.h\&.
.SS "#define INV2_TX_GPIO_Port   GPIOB"

.PP
Definition at line 82 of file main\&.h\&.
.SS "#define INV2_TX_Pin   GPIO_PIN_6"

.PP
Definition at line 81 of file main\&.h\&.
.SS "#define LD1_GPIO_Port   GPIOB"

.PP
Definition at line 72 of file main\&.h\&.
.SS "#define LD1_Pin   GPIO_PIN_0"

.PP
Definition at line 71 of file main\&.h\&.
.SS "#define LD3_GPIO_Port   GPIOB"

.PP
Definition at line 76 of file main\&.h\&.
.SS "#define LD3_Pin   GPIO_PIN_14"

.PP
Definition at line 75 of file main\&.h\&.
.SS "#define SysEl_RX_GPIO_Port   GPIOA"

.PP
Definition at line 78 of file main\&.h\&.
.SS "#define SysEl_RX_Pin   GPIO_PIN_11"

.PP
Definition at line 77 of file main\&.h\&.
.SS "#define SysEl_TX_GPIO_Port   GPIOA"

.PP
Definition at line 80 of file main\&.h\&.
.SS "#define SysEl_TX_Pin   GPIO_PIN_12"

.PP
Definition at line 79 of file main\&.h\&.
.SS "#define Throttle_IN1_GPIO_Port   GPIOA"

.PP
Definition at line 68 of file main\&.h\&.
.SS "#define Throttle_IN1_Pin   GPIO_PIN_0"

.PP
Definition at line 67 of file main\&.h\&.
.SS "#define Throttle_IN2_GPIO_Port   GPIOA"

.PP
Definition at line 70 of file main\&.h\&.
.SS "#define Throttle_IN2_Pin   GPIO_PIN_1"

.PP
Definition at line 69 of file main\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void Error_Handler (void)"

.PP
This function is executed in case of error occurrence\&. 
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 166 of file main\&.cpp\&.
.PP
Referenced by MX_ADC1_Init(), MX_CAN1_Init(), MX_CAN2_Init(), and SystemClock_Config()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
