C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/src/main.c
NAME
C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/src/main.c - : Main program body
SYNOPSIS
#include 'main.h'
#include 'adc.h'
#include 'can.h'
#include 'gpio.h'
Functions
void SystemClock_Config (void)
System Clock Configuration.
int main (void)
The application entry point.
void Error_Handler (void)
This function is executed in case of error occurrence.
Detailed Description
: Main program body
Attention
(C) Copyright (c) 2019 STMicroelectronics. All rights reserved.
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License. You may obtain a copy of the License at: opensource.org/licenses/BSD-3-Clause
Definition in file main.c.
Function Documentation
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 157 of file main.c.
Referenced by MX_ADC1_Init(), MX_CAN1_Init(), MX_CAN2_Init(), MX_CAN3_Init(), and SystemClock_Config().
int main (void)
The application entry point.
Return values
int
Definition at line 67 of file main.c.
References MX_ADC1_Init(), MX_CAN1_Init(), MX_CAN2_Init(), MX_CAN3_Init(), MX_GPIO_Init(), and SystemClock_Config().
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Configure the main internal regulator output voltage
Initializes the CPU, AHB and APB busses clocks
Initializes the CPU, AHB and APB busses clocks
Definition at line 115 of file main.c.
References Error_Handler().
Referenced by main().
Author
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code.