/Users/maurice/git/VCU-STM32F767ZI/inc/main.h
NAME
/Users/maurice/git/VCU-STM32F767ZI/inc/main.h - : Header for main.c file. This file contains the common defines of the application.
SYNOPSIS
#include 'stm32f7xx_hal.h'
Macros
#define BOTS_Pin GPIO_PIN_1
#define BOTS_GPIO_Port GPIOF
#define HVOK_IN_Pin GPIO_PIN_2
#define HVOK_IN_GPIO_Port GPIOF
#define HV_unlock_Pin GPIO_PIN_3
#define HV_unlock_GPIO_Port GPIOF
#define Throttle_IN1_Pin GPIO_PIN_0
#define Throttle_IN1_GPIO_Port GPIOA
#define Throttle_IN2_Pin GPIO_PIN_1
#define Throttle_IN2_GPIO_Port GPIOA
#define LD1_Pin GPIO_PIN_0
#define LD1_GPIO_Port GPIOB
#define INV1_RX_Pin GPIO_PIN_12
#define INV1_RX_GPIO_Port GPIOB
#define LD3_Pin GPIO_PIN_14
#define LD3_GPIO_Port GPIOB
#define SysEl_RX_Pin GPIO_PIN_11
#define SysEl_RX_GPIO_Port GPIOA
#define SysEl_TX_Pin GPIO_PIN_12
#define SysEl_TX_GPIO_Port GPIOA
#define INV2_TX_Pin GPIO_PIN_6
#define INV2_TX_GPIO_Port GPIOB
Functions
void Error_Handler (void)
This function is executed in case of error occurrence.
Detailed Description
: Header for main.c file. This file contains the common defines of the application.
Attention
(C) Copyright (c) 2019 STMicroelectronics. All rights reserved.
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License. You may obtain a copy of the License at: opensource.org/licenses/BSD-3-Clause
Definition in file main.h.
Macro Definition Documentation
#define BOTS_GPIO_Port GPIOF
Definition at line 62 of file main.h.
#define BOTS_Pin GPIO_PIN_1
Definition at line 61 of file main.h.
#define HV_unlock_GPIO_Port GPIOF
Definition at line 66 of file main.h.
#define HV_unlock_Pin GPIO_PIN_3
Definition at line 65 of file main.h.
#define HVOK_IN_GPIO_Port GPIOF
Definition at line 64 of file main.h.
#define HVOK_IN_Pin GPIO_PIN_2
Definition at line 63 of file main.h.
#define INV1_RX_GPIO_Port GPIOB
Definition at line 74 of file main.h.
#define INV1_RX_Pin GPIO_PIN_12
Definition at line 73 of file main.h.
#define INV2_TX_GPIO_Port GPIOB
Definition at line 82 of file main.h.
#define INV2_TX_Pin GPIO_PIN_6
Definition at line 81 of file main.h.
#define LD1_GPIO_Port GPIOB
Definition at line 72 of file main.h.
#define LD1_Pin GPIO_PIN_0
Definition at line 71 of file main.h.
#define LD3_GPIO_Port GPIOB
Definition at line 76 of file main.h.
#define LD3_Pin GPIO_PIN_14
Definition at line 75 of file main.h.
#define SysEl_RX_GPIO_Port GPIOA
Definition at line 78 of file main.h.
#define SysEl_RX_Pin GPIO_PIN_11
Definition at line 77 of file main.h.
#define SysEl_TX_GPIO_Port GPIOA
Definition at line 80 of file main.h.
#define SysEl_TX_Pin GPIO_PIN_12
Definition at line 79 of file main.h.
#define Throttle_IN1_GPIO_Port GPIOA
Definition at line 68 of file main.h.
#define Throttle_IN1_Pin GPIO_PIN_0
Definition at line 67 of file main.h.
#define Throttle_IN2_GPIO_Port GPIOA
Definition at line 70 of file main.h.
#define Throttle_IN2_Pin GPIO_PIN_1
Definition at line 69 of file main.h.
Function Documentation
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 166 of file main.cpp.
Referenced by MX_ADC1_Init(), MX_CAN1_Init(), MX_CAN2_Init(), and SystemClock_Config().
Author
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code.