/Users/maurice/git/VCU-STM32F767ZI/src/main.cpp
NAME
/Users/maurice/git/VCU-STM32F767ZI/src/main.cpp
SYNOPSIS
#include 'main.h'
#include 'adc.h'
#include 'can.h'
#include 'gpio.h'
#include <Header_VCU/Sensors.h>
Functions
void SystemClock_Config (void)
System Clock Configuration.
int _write (int file, char *ptr, int len)
int main (void)
The application entry point.
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
Sensors Sensors
Function Documentation
int _write (int file, char * ptr, int len)
Definition at line 61 of file main.cpp.
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 166 of file main.cpp.
Referenced by MX_ADC1_Init(), MX_CAN1_Init(), MX_CAN2_Init(), and SystemClock_Config().
int main (void)
The application entry point.
Return values
int
Definition at line 79 of file main.cpp.
References MX_ADC1_Init(), MX_CAN1_Init(), MX_CAN2_Init(), MX_GPIO_Init(), and SystemClock_Config().
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Configure the main internal regulator output voltage
Initializes the CPU, AHB and APB busses clocks
Initializes the CPU, AHB and APB busses clocks
Definition at line 124 of file main.cpp.
References Error_Handler().
Referenced by main().
Variable Documentation
Sensors Sensors
Definition at line 50 of file main.cpp.
Author
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code.