.TH "/Users/maurice/git/VCU-STM32F767ZI/inc/Header_VCU/Sensors.h" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maurice/git/VCU-STM32F767ZI/inc/Header_VCU/Sensors.h \- This file contains all \fBSensors\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'canTempSensor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSensors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains all \fBSensors\fP\&. 


.PP
\fBAuthor\fP
.RS 4
Maurice Hugenschmidt
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
This Header contains all \fBSensors\fP 
.PP
Definition in file \fBSensors\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
