.TH "C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/inc/Sensors.h" 3 "Fri Dec 13 2019" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/inc/Sensors.h \- : This file contains an Abstract for sensors  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSensors< T >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
: This file contains an Abstract for sensors 


.PP
\fBAuthor\fP
.RS 4
: Maurice Hugenschmidt
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
Each sensor class have to include this header as Mother class 
.PP
Definition in file \fBSensors\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
