.TH "Sensors" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sensors
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sensors\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSensors\fP ()"
.br
.ti -1c
.RI "\fB~Sensors\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcanTempSensor\fP \fBcoolantTemp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file Sensors\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sensors::Sensors ()"

.PP
Definition at line 20 of file Sensors\&.cpp\&.
.SS "Sensors::~Sensors ()"

.PP
Definition at line 26 of file Sensors\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBcanTempSensor\fP Sensors::coolantTemp"

.PP
Definition at line 37 of file Sensors\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
