.TH "STM32F7xx_System_Private_Includes" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F7xx_System_Private_Includes
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHSE_VALUE\fP   ((uint32_t)25000000)"
.br
.ti -1c
.RI "#define \fBHSI_VALUE\fP   ((uint32_t)16000000)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HSE_VALUE   ((uint32_t)25000000)"
Default value of the External oscillator in Hz 
.PP
Definition at line 67 of file system_stm32f7xx\&.c\&.
.SS "#define HSI_VALUE   ((uint32_t)16000000)"
Value of the Internal oscillator in Hz 
.PP
Definition at line 71 of file system_stm32f7xx\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
