.TH "STM32F7xx_System_Private_Variables" 3 "Fri Dec 13 2019" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F7xx_System_Private_Variables
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP = 16000000"
.br
.ti -1c
.RI "const uint8_t \fBAHBPrescTable\fP [16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9}"
.br
.ti -1c
.RI "const uint8_t \fBAPBPrescTable\fP [8] = {0, 0, 0, 0, 1, 2, 3, 4}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Variable Documentation"
.PP 
.SS "const uint8_t AHBPrescTable[16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9}"

.PP
Definition at line 125 of file system_stm32f7xx\&.c\&.
.PP
Referenced by SystemCoreClockUpdate()\&.
.SS "const uint8_t APBPrescTable[8] = {0, 0, 0, 0, 1, 2, 3, 4}"

.PP
Definition at line 126 of file system_stm32f7xx\&.c\&.
.SS "uint32_t SystemCoreClock = 16000000"

.PP
Definition at line 124 of file system_stm32f7xx\&.c\&.
.PP
Referenced by SystemCoreClockUpdate()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
