.TH "/Users/maurice/git/VCU-STM32F767ZI/inc/stm32f7xx_hal_conf.h" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maurice/git/VCU-STM32F767ZI/inc/stm32f7xx_hal_conf.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f7xx_hal_rcc\&.h'\fP
.br
\fC#include 'stm32f7xx_hal_exti\&.h'\fP
.br
\fC#include 'stm32f7xx_hal_gpio\&.h'\fP
.br
\fC#include 'stm32f7xx_hal_dma\&.h'\fP
.br
\fC#include 'stm32f7xx_hal_cortex\&.h'\fP
.br
\fC#include 'stm32f7xx_hal_adc\&.h'\fP
.br
\fC#include 'stm32f7xx_hal_can\&.h'\fP
.br
\fC#include 'stm32f7xx_hal_flash\&.h'\fP
.br
\fC#include 'stm32f7xx_hal_i2c\&.h'\fP
.br
\fC#include 'stm32f7xx_hal_pwr\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_MODULE_ENABLED\fP"
.br
.RI "This is the list of modules to be used in the HAL driver\&. "
.ti -1c
.RI "#define \fBHAL_ADC_MODULE_ENABLED\fP"
.br
.ti -1c
.RI "#define \fBHAL_CAN_MODULE_ENABLED\fP"
.br
.ti -1c
.RI "#define \fBHAL_GPIO_MODULE_ENABLED\fP"
.br
.ti -1c
.RI "#define \fBHAL_EXTI_MODULE_ENABLED\fP"
.br
.ti -1c
.RI "#define \fBHAL_DMA_MODULE_ENABLED\fP"
.br
.ti -1c
.RI "#define \fBHAL_RCC_MODULE_ENABLED\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_MODULE_ENABLED\fP"
.br
.ti -1c
.RI "#define \fBHAL_PWR_MODULE_ENABLED\fP"
.br
.ti -1c
.RI "#define \fBHAL_I2C_MODULE_ENABLED\fP"
.br
.ti -1c
.RI "#define \fBHAL_CORTEX_MODULE_ENABLED\fP"
.br
.ti -1c
.RI "#define \fBHSE_VALUE\fP   ((uint32_t)16000000U)"
.br
.RI "Adjust the value of External High Speed oscillator (HSE) used in your application\&. This value is used by the RCC HAL module to compute the system frequency (when HSE is used as system clock source, directly or through the PLL)\&. 
.br
 "
.ti -1c
.RI "#define \fBHSE_STARTUP_TIMEOUT\fP   ((uint32_t)100U)"
.br
.ti -1c
.RI "#define \fBHSI_VALUE\fP   ((uint32_t)16000000U)"
.br
.RI "Internal High Speed oscillator (HSI) value\&. This value is used by the RCC HAL module to compute the system frequency (when HSI is used as system clock source, directly or through the PLL)\&. "
.ti -1c
.RI "#define \fBLSI_VALUE\fP   ((uint32_t)32000U)"
.br
.RI "Internal Low Speed oscillator (LSI) value\&. "
.ti -1c
.RI "#define \fBLSE_VALUE\fP   ((uint32_t)32768U)"
.br
.RI "External Low Speed oscillator (LSE) value\&. "
.ti -1c
.RI "#define \fBLSE_STARTUP_TIMEOUT\fP   ((uint32_t)5000U)"
.br
.ti -1c
.RI "#define \fBEXTERNAL_CLOCK_VALUE\fP   ((uint32_t)12288000U)"
.br
.RI "External clock source for I2S peripheral This value is used by the I2S HAL module to compute the I2S clock source frequency, this source is inserted directly through I2S_CKIN pad\&. "
.ti -1c
.RI "#define \fBVDD_VALUE\fP   ((uint32_t)3300U)"
.br
.RI "This is the HAL system configuration section\&. "
.ti -1c
.RI "#define \fBTICK_INT_PRIORITY\fP   ((uint32_t)0U)"
.br
.ti -1c
.RI "#define \fBUSE_RTOS\fP   0U"
.br
.ti -1c
.RI "#define \fBPREFETCH_ENABLE\fP   0U"
.br
.ti -1c
.RI "#define \fBART_ACCLERATOR_ENABLE\fP   0U /* To enable instruction cache and prefetch */"
.br
.ti -1c
.RI "#define \fBMAC_ADDR0\fP   2U"
.br
.RI "Uncomment the line below to expanse the 'assert_param' macro in the HAL drivers code\&. "
.ti -1c
.RI "#define \fBMAC_ADDR1\fP   0U"
.br
.ti -1c
.RI "#define \fBMAC_ADDR2\fP   0U"
.br
.ti -1c
.RI "#define \fBMAC_ADDR3\fP   0U"
.br
.ti -1c
.RI "#define \fBMAC_ADDR4\fP   0U"
.br
.ti -1c
.RI "#define \fBMAC_ADDR5\fP   0U"
.br
.ti -1c
.RI "#define \fBETH_RX_BUF_SIZE\fP   ETH_MAX_PACKET_SIZE /* buffer size for receive               */"
.br
.ti -1c
.RI "#define \fBETH_TX_BUF_SIZE\fP   ETH_MAX_PACKET_SIZE /* buffer size for transmit              */"
.br
.ti -1c
.RI "#define \fBETH_RXBUFNB\fP   ((uint32_t)4U)       /* 4 Rx buffers of size \fBETH_RX_BUF_SIZE\fP  */"
.br
.ti -1c
.RI "#define \fBETH_TXBUFNB\fP   ((uint32_t)4U)       /* 4 Tx buffers of size \fBETH_TX_BUF_SIZE\fP  */"
.br
.ti -1c
.RI "#define \fBDP83848_PHY_ADDRESS\fP   0x01U"
.br
.ti -1c
.RI "#define \fBPHY_RESET_DELAY\fP   ((uint32_t)0x000000FFU)"
.br
.ti -1c
.RI "#define \fBPHY_CONFIG_DELAY\fP   ((uint32_t)0x00000FFFU)"
.br
.ti -1c
.RI "#define \fBPHY_READ_TO\fP   ((uint32_t)0x0000FFFFU)"
.br
.ti -1c
.RI "#define \fBPHY_WRITE_TO\fP   ((uint32_t)0x0000FFFFU)"
.br
.ti -1c
.RI "#define \fBPHY_BCR\fP   ((uint16_t)0x0000U)"
.br
.ti -1c
.RI "#define \fBPHY_BSR\fP   ((uint16_t)0x0001U)"
.br
.ti -1c
.RI "#define \fBPHY_RESET\fP   ((uint16_t)0x8000U)"
.br
.ti -1c
.RI "#define \fBPHY_LOOPBACK\fP   ((uint16_t)0x4000U)"
.br
.ti -1c
.RI "#define \fBPHY_FULLDUPLEX_100M\fP   ((uint16_t)0x2100U)"
.br
.ti -1c
.RI "#define \fBPHY_HALFDUPLEX_100M\fP   ((uint16_t)0x2000U)"
.br
.ti -1c
.RI "#define \fBPHY_FULLDUPLEX_10M\fP   ((uint16_t)0x0100U)"
.br
.ti -1c
.RI "#define \fBPHY_HALFDUPLEX_10M\fP   ((uint16_t)0x0000U)"
.br
.ti -1c
.RI "#define \fBPHY_AUTONEGOTIATION\fP   ((uint16_t)0x1000U)"
.br
.ti -1c
.RI "#define \fBPHY_RESTART_AUTONEGOTIATION\fP   ((uint16_t)0x0200U)"
.br
.ti -1c
.RI "#define \fBPHY_POWERDOWN\fP   ((uint16_t)0x0800U)"
.br
.ti -1c
.RI "#define \fBPHY_ISOLATE\fP   ((uint16_t)0x0400U)"
.br
.ti -1c
.RI "#define \fBPHY_AUTONEGO_COMPLETE\fP   ((uint16_t)0x0020U)"
.br
.ti -1c
.RI "#define \fBPHY_LINKED_STATUS\fP   ((uint16_t)0x0004U)"
.br
.ti -1c
.RI "#define \fBPHY_JABBER_DETECTION\fP   ((uint16_t)0x0002U)"
.br
.ti -1c
.RI "#define \fBPHY_SR\fP   ((uint16_t)0x10U)"
.br
.ti -1c
.RI "#define \fBPHY_SPEED_STATUS\fP   ((uint16_t)0x0002U)"
.br
.ti -1c
.RI "#define \fBPHY_DUPLEX_STATUS\fP   ((uint16_t)0x0004U)"
.br
.ti -1c
.RI "#define \fBUSE_SPI_CRC\fP   0U"
.br
.ti -1c
.RI "#define \fBassert_param\fP(expr)   ((void)0U)"
.br
.RI "Include module's header file\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ART_ACCLERATOR_ENABLE   0U /* To enable instruction cache and prefetch */"

.PP
Definition at line 151 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define assert_param(expr)   ((void)0U)"

.PP
Include module's header file\&. 
.PP
Definition at line 432 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define DP83848_PHY_ADDRESS   0x01U"

.PP
Definition at line 181 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define ETH_RX_BUF_SIZE   ETH_MAX_PACKET_SIZE /* buffer size for receive               */"

.PP
Definition at line 173 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define ETH_RXBUFNB   ((uint32_t)4U)       /* 4 Rx buffers of size \fBETH_RX_BUF_SIZE\fP  */"

.PP
Definition at line 175 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define ETH_TX_BUF_SIZE   ETH_MAX_PACKET_SIZE /* buffer size for transmit              */"

.PP
Definition at line 174 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define ETH_TXBUFNB   ((uint32_t)4U)       /* 4 Tx buffers of size \fBETH_TX_BUF_SIZE\fP  */"

.PP
Definition at line 176 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define EXTERNAL_CLOCK_VALUE   ((uint32_t)12288000U)"

.PP
External clock source for I2S peripheral This value is used by the I2S HAL module to compute the I2S clock source frequency, this source is inserted directly through I2S_CKIN pad\&. Value of the Internal oscillator in Hz 
.PP
Definition at line 137 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HAL_ADC_MODULE_ENABLED"

.PP
Definition at line 39 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HAL_CAN_MODULE_ENABLED"

.PP
Definition at line 41 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HAL_CORTEX_MODULE_ENABLED"

.PP
Definition at line 87 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HAL_DMA_MODULE_ENABLED"

.PP
Definition at line 82 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HAL_EXTI_MODULE_ENABLED"

.PP
Definition at line 81 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HAL_FLASH_MODULE_ENABLED"

.PP
Definition at line 84 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HAL_GPIO_MODULE_ENABLED"

.PP
Definition at line 80 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HAL_I2C_MODULE_ENABLED"

.PP
Definition at line 86 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HAL_MODULE_ENABLED"

.PP
This is the list of modules to be used in the HAL driver\&. 
.PP
Definition at line 37 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HAL_PWR_MODULE_ENABLED"

.PP
Definition at line 85 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HAL_RCC_MODULE_ENABLED"

.PP
Definition at line 83 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HSE_STARTUP_TIMEOUT   ((uint32_t)100U)"
Time out for HSE start up, in ms 
.PP
Definition at line 100 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HSE_VALUE   ((uint32_t)16000000U)"

.PP
Adjust the value of External High Speed oscillator (HSE) used in your application\&. This value is used by the RCC HAL module to compute the system frequency (when HSE is used as system clock source, directly or through the PLL)\&. 
.br
 Value of the External oscillator in Hz 
.PP
Definition at line 96 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define HSI_VALUE   ((uint32_t)16000000U)"

.PP
Internal High Speed oscillator (HSI) value\&. This value is used by the RCC HAL module to compute the system frequency (when HSI is used as system clock source, directly or through the PLL)\&. Value of the Internal oscillator in Hz 
.PP
Definition at line 109 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define LSE_STARTUP_TIMEOUT   ((uint32_t)5000U)"
Time out for LSE start up, in ms 
.PP
Definition at line 128 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define LSE_VALUE   ((uint32_t)32768U)"

.PP
External Low Speed oscillator (LSE) value\&. < Value of the Internal Low Speed oscillator in Hz The real value may vary depending on the variations in voltage and temperature\&. 
.br
 Value of the External Low Speed oscillator in Hz 
.PP
Definition at line 124 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define LSI_VALUE   ((uint32_t)32000U)"

.PP
Internal Low Speed oscillator (LSI) value\&. LSI Typical Value in Hz 
.PP
Definition at line 116 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define MAC_ADDR0   2U"

.PP
Uncomment the line below to expanse the 'assert_param' macro in the HAL drivers code\&. 
.PP
Definition at line 165 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define MAC_ADDR1   0U"

.PP
Definition at line 166 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define MAC_ADDR2   0U"

.PP
Definition at line 167 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define MAC_ADDR3   0U"

.PP
Definition at line 168 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define MAC_ADDR4   0U"

.PP
Definition at line 169 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define MAC_ADDR5   0U"

.PP
Definition at line 170 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_AUTONEGO_COMPLETE   ((uint16_t)0x0020U)"
Auto-Negotiation process completed 
.br
 
.PP
Definition at line 206 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_AUTONEGOTIATION   ((uint16_t)0x1000U)"
Enable auto-negotiation function 
.br
 
.PP
Definition at line 201 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_BCR   ((uint16_t)0x0000U)"
Transceiver Basic Control Register 
.br
 
.PP
Definition at line 192 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_BSR   ((uint16_t)0x0001U)"
Transceiver Basic Status Register 
.br
 
.PP
Definition at line 193 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_CONFIG_DELAY   ((uint32_t)0x00000FFFU)"

.PP
Definition at line 185 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_DUPLEX_STATUS   ((uint16_t)0x0004U)"
PHY Duplex mask 
.br
 
.PP
Definition at line 214 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_FULLDUPLEX_100M   ((uint16_t)0x2100U)"
Set the full-duplex mode at 100 Mb/s 
.PP
Definition at line 197 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_FULLDUPLEX_10M   ((uint16_t)0x0100U)"
Set the full-duplex mode at 10 Mb/s 
.br
 
.PP
Definition at line 199 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_HALFDUPLEX_100M   ((uint16_t)0x2000U)"
Set the half-duplex mode at 100 Mb/s 
.PP
Definition at line 198 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_HALFDUPLEX_10M   ((uint16_t)0x0000U)"
Set the half-duplex mode at 10 Mb/s 
.br
 
.PP
Definition at line 200 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_ISOLATE   ((uint16_t)0x0400U)"
Isolate PHY from MII 
.br
 
.PP
Definition at line 204 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_JABBER_DETECTION   ((uint16_t)0x0002U)"
Jabber condition detected 
.br
 
.PP
Definition at line 208 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_LINKED_STATUS   ((uint16_t)0x0004U)"
Valid link established 
.br
 
.PP
Definition at line 207 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_LOOPBACK   ((uint16_t)0x4000U)"
Select loop-back mode 
.PP
Definition at line 196 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_POWERDOWN   ((uint16_t)0x0800U)"
Select the power down mode 
.br
 
.PP
Definition at line 203 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_READ_TO   ((uint32_t)0x0000FFFFU)"

.PP
Definition at line 187 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_RESET   ((uint16_t)0x8000U)"
PHY Reset 
.PP
Definition at line 195 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_RESET_DELAY   ((uint32_t)0x000000FFU)"

.PP
Definition at line 183 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_RESTART_AUTONEGOTIATION   ((uint16_t)0x0200U)"
Restart auto-negotiation function 
.br
 
.PP
Definition at line 202 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_SPEED_STATUS   ((uint16_t)0x0002U)"
PHY Speed mask 
.br
 
.PP
Definition at line 213 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_SR   ((uint16_t)0x10U)"
PHY status register Offset 
.br
 
.PP
Definition at line 211 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PHY_WRITE_TO   ((uint32_t)0x0000FFFFU)"

.PP
Definition at line 188 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define PREFETCH_ENABLE   0U"

.PP
Definition at line 150 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define TICK_INT_PRIORITY   ((uint32_t)0U)"
tick interrupt priority 
.PP
Definition at line 148 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define USE_RTOS   0U"

.PP
Definition at line 149 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define USE_SPI_CRC   0U"

.PP
Definition at line 223 of file stm32f7xx_hal_conf\&.h\&.
.SS "#define VDD_VALUE   ((uint32_t)3300U)"

.PP
This is the HAL system configuration section\&. Value of VDD in mv 
.PP
Definition at line 147 of file stm32f7xx_hal_conf\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
