.TH "STM32F7xx_System_Private_Defines" 3 "Fri Dec 13 2019" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F7xx_System_Private_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVECT_TAB_OFFSET\fP   0x00"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define VECT_TAB_OFFSET   0x00"
< Uncomment the following line if you need to relocate your vector Table in Internal SRAM\&. Vector Table base offset field\&. This value must be a multiple of 0x200\&. 
.PP
Definition at line 95 of file system_stm32f7xx\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
