.TH "/Users/maurice/git/VCU-STM32F767ZI/src/sys.c" 3 "Wed Jan 15 2020" "BFFT_VCU_V1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/maurice/git/VCU-STM32F767ZI/src/sys.c
.SH SYNOPSIS
.br
.PP
\fC#include 'sys\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_SYS_Init\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void MX_SYS_Init (void)"
File Name : \fBSYS\&.c\fP Description : This file provides code for the configuration of the SYS instances\&.
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2019 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
Definition at line 28 of file sys\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code\&.
