C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/src/syscalls.c
NAME
C:/Users/BFFT_Konstr_3/Documents/STM_Board_Config/BFFT_VCU_V1/src/syscalls.c
SYNOPSIS
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>
Functions
int __io_putchar (int ch) __attribute__((weak))
int __io_getchar (void)
void initialise_monitor_handles ()
int _getpid (void)
int _kill (int pid, int sig)
void _exit (int status)
__attribute__ ((weak))
int _close (int file)
int _fstat (int file, struct stat *st)
int _isatty (int file)
int _lseek (int file, int ptr, int dir)
int _open (char *path, int flags,...)
int _wait (int *status)
int _unlink (char *name)
int _times (struct tms *buf)
int _stat (char *file, struct stat *st)
int _link (char *old, char *new)
int _fork (void)
int _execve (char *name, char **argv, char **env)
Variables
int errno
char ** environ = __env
Function Documentation
__attribute__ ((weak))
Definition at line 94 of file syscalls.c.
References __io_getchar().
int __io_getchar (void)
Definition at line 64 of file syscalls.c.
Referenced by __attribute__().
int __io_putchar (int ch)
int _close (int file)
Definition at line 117 of file syscalls.c.
int _execve (char * name, char ** argv, char ** env)
Definition at line 180 of file syscalls.c.
References errno.
void _exit (int status)
Definition at line 88 of file syscalls.c.
References _kill().
int _fork (void)
Definition at line 174 of file syscalls.c.
References errno.
int _fstat (int file, struct stat * st)
Definition at line 123 of file syscalls.c.
int _getpid (void)
Definition at line 77 of file syscalls.c.
int _isatty (int file)
Definition at line 129 of file syscalls.c.
int _kill (int pid, int sig)
Definition at line 82 of file syscalls.c.
References errno.
Referenced by _exit().
int _link (char * old, char * new)
Definition at line 168 of file syscalls.c.
References errno.
int _lseek (int file, int ptr, int dir)
Definition at line 134 of file syscalls.c.
int _open (char * path, int flags, ...)
Definition at line 139 of file syscalls.c.
int _stat (char * file, struct stat * st)
Definition at line 162 of file syscalls.c.
int _times (struct tms * buf)
Definition at line 157 of file syscalls.c.
int _unlink (char * name)
Definition at line 151 of file syscalls.c.
References errno.
int _wait (int * status)
Definition at line 145 of file syscalls.c.
References errno.
void initialise_monitor_handles ()
Definition at line 73 of file syscalls.c.
Variable Documentation
char** environ = __env
Definition at line 69 of file syscalls.c.
int errno
File : syscalls.c
Author : Auto-generated by STM32CubeIDE
Abstract : STM32CubeIDE Minimal System calls file
             For more information about which c-functions
          need which of these lowlevel functions
          please consult the Newlib libc-manual
Environment : STM32CubeIDE MCU
Distribution: The file is distributed as is, without any warranty of any kind.
(C) COPYRIGHT(c) 2018 STMicroelectronics
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1.
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3.
Neither the name of STMicroelectronics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Referenced by _execve(), _fork(), _kill(), _link(), _unlink(), and _wait().
Author
Generated automatically by Doxygen for BFFT_VCU_V1 from the source code.