var modules =
[
    [ "CMSIS Global Defines", "group___c_m_s_i_s__glob__defs.html", null ],
    [ "Defines and Type Definitions", "group___c_m_s_i_s__core__register.html", "group___c_m_s_i_s__core__register" ],
    [ "HAL CRYP Aliased Defines maintained for legacy purpose", "group___h_a_l___a_e_s___aliased___defines.html", null ],
    [ "HAL ADC Aliased Defines maintained for legacy purpose", "group___h_a_l___a_d_c___aliased___defines.html", null ],
    [ "HAL CEC Aliased Defines maintained for legacy purpose", "group___h_a_l___c_e_c___aliased___defines.html", null ],
    [ "HAL COMP Aliased Defines maintained for legacy purpose", "group___h_a_l___c_o_m_p___aliased___defines.html", null ],
    [ "HAL CORTEX Aliased Defines maintained for legacy purpose", "group___h_a_l___c_o_r_t_e_x___aliased___defines.html", null ],
    [ "HAL CRC Aliased Defines maintained for legacy purpose", "group___h_a_l___c_r_c___aliased___defines.html", null ],
    [ "HAL DAC Aliased Defines maintained for legacy purpose", "group___h_a_l___d_a_c___aliased___defines.html", null ],
    [ "HAL DMA Aliased Defines maintained for legacy purpose", "group___h_a_l___d_m_a___aliased___defines.html", null ],
    [ "HAL FLASH Aliased Defines maintained for legacy purpose", "group___h_a_l___f_l_a_s_h___aliased___defines.html", null ],
    [ "HAL JPEG Aliased Macros maintained for legacy purpose", "group___h_a_l___j_p_e_g___aliased___macros.html", null ],
    [ "HAL SYSCFG Aliased Defines maintained for legacy purpose", "group___h_a_l___s_y_s_c_f_g___aliased___defines.html", null ],
    [ "LL FMC Aliased Defines maintained for compatibility purpose", "group___l_l___f_m_c___aliased___defines.html", null ],
    [ "LL FSMC Aliased Defines maintained for legacy purpose", "group___l_l___f_s_m_c___aliased___defines.html", null ],
    [ "HAL GPIO Aliased Macros maintained for legacy purpose", "group___h_a_l___g_p_i_o___aliased___macros.html", null ],
    [ "HAL HRTIM Aliased Macros maintained for legacy purpose", "group___h_a_l___h_r_t_i_m___aliased___macros.html", null ],
    [ "HAL I2C Aliased Defines maintained for legacy purpose", "group___h_a_l___i2_c___aliased___defines.html", null ],
    [ "HAL IRDA Aliased Defines maintained for legacy purpose", "group___h_a_l___i_r_d_a___aliased___defines.html", null ],
    [ "HAL IWDG Aliased Defines maintained for legacy purpose", "group___h_a_l___i_w_d_g___aliased___defines.html", null ],
    [ "HAL LPTIM Aliased Defines maintained for legacy purpose", "group___h_a_l___l_p_t_i_m___aliased___defines.html", null ],
    [ "HAL NAND Aliased Defines maintained for legacy purpose", "group___h_a_l___n_a_n_d___aliased___defines.html", null ],
    [ "HAL NOR Aliased Defines maintained for legacy purpose", "group___h_a_l___n_o_r___aliased___defines.html", null ],
    [ "HAL OPAMP Aliased Defines maintained for legacy purpose", "group___h_a_l___o_p_a_m_p___aliased___defines.html", null ],
    [ "HAL I2S Aliased Defines maintained for legacy purpose", "group___h_a_l___i2_s___aliased___defines.html", null ],
    [ "HAL PCCARD Aliased Defines maintained for legacy purpose", "group___h_a_l___p_c_c_a_r_d___aliased___defines.html", null ],
    [ "HAL RTC Aliased Defines maintained for legacy purpose", "group___h_a_l___r_t_c___aliased___defines.html", null ],
    [ "HAL SMARTCARD Aliased Defines maintained for legacy purpose", "group___h_a_l___s_m_a_r_t_c_a_r_d___aliased___defines.html", null ],
    [ "HAL SMBUS Aliased Defines maintained for legacy purpose", "group___h_a_l___s_m_b_u_s___aliased___defines.html", null ],
    [ "HAL SPI Aliased Defines maintained for legacy purpose", "group___h_a_l___s_p_i___aliased___defines.html", null ],
    [ "HAL TIM Aliased Defines maintained for legacy purpose", "group___h_a_l___t_i_m___aliased___defines.html", null ],
    [ "HAL TSC Aliased Defines maintained for legacy purpose", "group___h_a_l___t_s_c___aliased___defines.html", null ],
    [ "HAL UART Aliased Defines maintained for legacy purpose", "group___h_a_l___u_a_r_t___aliased___defines.html", null ],
    [ "HAL USART Aliased Defines maintained for legacy purpose", "group___h_a_l___u_s_a_r_t___aliased___defines.html", null ],
    [ "HAL WWDG Aliased Defines maintained for legacy purpose", "group___h_a_l___w_w_d_g___aliased___defines.html", null ],
    [ "HAL CAN Aliased Defines maintained for legacy purpose", "group___h_a_l___c_a_n___aliased___defines.html", null ],
    [ "HAL ETH Aliased Defines maintained for legacy purpose", "group___h_a_l___e_t_h___aliased___defines.html", null ],
    [ "HAL DCMI Aliased Defines maintained for legacy purpose", "group___h_a_l___d_c_m_i___aliased___defines.html", null ],
    [ "HAL PPP Aliased Defines maintained for legacy purpose", "group___h_a_l___p_p_p___aliased___defines.html", null ],
    [ "HAL CRYP Aliased Functions maintained for legacy purpose", "group___h_a_l___c_r_y_p___aliased___functions.html", null ],
    [ "HAL HASH Aliased Functions maintained for legacy purpose", "group___h_a_l___h_a_s_h___aliased___functions.html", null ],
    [ "HAL Generic Aliased Functions maintained for legacy purpose", "group___h_a_l___aliased___functions.html", null ],
    [ "HAL FLASH Aliased Functions maintained for legacy purpose", "group___h_a_l___f_l_a_s_h___aliased___functions.html", null ],
    [ "HAL I2C Aliased Functions maintained for legacy purpose", "group___h_a_l___i2_c___aliased___functions.html", null ],
    [ "HAL PWR Aliased maintained for legacy purpose", "group___h_a_l___p_w_r___aliased.html", null ],
    [ "HAL SMBUS Aliased Functions maintained for legacy purpose", "group___h_a_l___s_m_b_u_s___aliased___functions.html", null ],
    [ "HAL SPI Aliased Functions maintained for legacy purpose", "group___h_a_l___s_p_i___aliased___functions.html", null ],
    [ "HAL TIM Aliased Functions maintained for legacy purpose", "group___h_a_l___t_i_m___aliased___functions.html", null ],
    [ "HAL UART Aliased Functions maintained for legacy purpose", "group___h_a_l___u_a_r_t___aliased___functions.html", null ],
    [ "HAL LTDC Aliased Functions maintained for legacy purpose", "group___h_a_l___l_t_d_c___aliased___functions.html", null ],
    [ "HAL PPP Aliased Functions maintained for legacy purpose", "group___h_a_l___p_p_p___aliased___functions.html", null ],
    [ "HAL CRYP Aliased Macros maintained for legacy purpose", "group___h_a_l___a_e_s___aliased___macros.html", null ],
    [ "HAL Generic Aliased Macros maintained for legacy purpose", "group___h_a_l___aliased___macros.html", null ],
    [ "HAL ADC Aliased Macros maintained for legacy purpose", "group___h_a_l___a_d_c___aliased___macros.html", null ],
    [ "HAL DAC Aliased Macros maintained for legacy purpose", "group___h_a_l___d_a_c___aliased___macros.html", null ],
    [ "HAL DBGMCU Aliased Macros maintained for legacy purpose", "group___h_a_l___d_b_g_m_c_u___aliased___macros.html", null ],
    [ "HAL COMP Aliased Macros maintained for legacy purpose", "group___h_a_l___c_o_m_p___aliased___macros.html", null ],
    [ "HAL FLASH Aliased Macros maintained for legacy purpose", "group___h_a_l___f_l_a_s_h___aliased___macros.html", null ],
    [ "HAL I2C Aliased Macros maintained for legacy purpose", "group___h_a_l___i2_c___aliased___macros.html", null ],
    [ "HAL I2S Aliased Macros maintained for legacy purpose", "group___h_a_l___i2_s___aliased___macros.html", null ],
    [ "HAL IRDA Aliased Macros maintained for legacy purpose", "group___h_a_l___i_r_d_a___aliased___macros.html", null ],
    [ "HAL IWDG Aliased Macros maintained for legacy purpose", "group___h_a_l___i_w_d_g___aliased___macros.html", null ],
    [ "HAL LPTIM Aliased Macros maintained for legacy purpose", "group___h_a_l___l_p_t_i_m___aliased___macros.html", null ],
    [ "HAL OPAMP Aliased Macros maintained for legacy purpose", "group___h_a_l___o_p_a_m_p___aliased___macros.html", null ],
    [ "HAL PWR Aliased Macros maintained for legacy purpose", "group___h_a_l___p_w_r___aliased___macros.html", null ],
    [ "HAL RCC Aliased maintained for legacy purpose", "group___h_a_l___r_c_c___aliased.html", null ],
    [ "HAL RNG Aliased Macros maintained for legacy purpose", "group___h_a_l___r_n_g___aliased___macros.html", null ],
    [ "HAL RTC Aliased Macros maintained for legacy purpose", "group___h_a_l___r_t_c___aliased___macros.html", null ],
    [ "HAL SD Aliased Macros maintained for legacy purpose", "group___h_a_l___s_d___aliased___macros.html", null ],
    [ "HAL SMARTCARD Aliased Macros maintained for legacy purpose", "group___h_a_l___s_m_a_r_t_c_a_r_d___aliased___macros.html", null ],
    [ "HAL SMBUS Aliased Macros maintained for legacy purpose", "group___h_a_l___s_m_b_u_s___aliased___macros.html", null ],
    [ "HAL SPI Aliased Macros maintained for legacy purpose", "group___h_a_l___s_p_i___aliased___macros.html", null ],
    [ "HAL UART Aliased Macros maintained for legacy purpose", "group___h_a_l___u_a_r_t___aliased___macros.html", null ],
    [ "HAL USART Aliased Macros maintained for legacy purpose", "group___h_a_l___u_s_a_r_t___aliased___macros.html", null ],
    [ "HAL USB Aliased Macros maintained for legacy purpose", "group___h_a_l___u_s_b___aliased___macros.html", null ],
    [ "HAL TIM Aliased Macros maintained for legacy purpose", "group___h_a_l___t_i_m___aliased___macros.html", null ],
    [ "HAL ETH Aliased Macros maintained for legacy purpose", "group___h_a_l___e_t_h___aliased___macros.html", null ],
    [ "HAL LTDC Aliased Macros maintained for legacy purpose", "group___h_a_l___l_t_d_c___aliased___macros.html", null ],
    [ "HAL SAI Aliased Macros maintained for legacy purpose", "group___h_a_l___s_a_i___aliased___macros.html", null ],
    [ "HAL SPDIFRX Aliased Macros maintained for legacy purpose", "group___h_a_l___s_p_d_i_f_r_x___aliased___macros.html", null ],
    [ "HAL HRTIM Aliased Functions maintained for legacy purpose", "group___h_a_l___h_r_t_i_m___aliased___functions.html", null ],
    [ "HAL QSPI Aliased Macros maintained for legacy purpose", "group___h_a_l___q_s_p_i___aliased___macros.html", null ],
    [ "HAL PPP Aliased Macros maintained for legacy purpose", "group___h_a_l___p_p_p___aliased___macros.html", null ],
    [ "CMSIS", "group___c_m_s_i_s.html", "group___c_m_s_i_s" ],
    [ "CMSIS_Device", "group___c_m_s_i_s___device.html", "group___c_m_s_i_s___device" ],
    [ "STM32F7xx_HAL_Driver", "group___s_t_m32_f7xx___h_a_l___driver.html", "group___s_t_m32_f7xx___h_a_l___driver" ],
    [ "STM32F7xx_LL_USB_DRIVER", "group___s_t_m32_f7xx___l_l___u_s_b___d_r_i_v_e_r.html", null ]
];